---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: santander-experience-backend
  labels:
    app: santander-experience-backend
spec:
  replicas: 50
  selector:
    matchLabels:
      app: santander-experience-backend
  template:
    metadata:
      labels:
        app: santander-experience-backend
    spec:
      containers:
      - name: santander-experience-backend
        image: YOUR_IMAGE
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: santander-experience-backend-service
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: santander-experience-backend
