---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: santander-experience-backend
  labels:
    app: santander-experience-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: santander-experience-backend
  template:
    metadata:
      labels:
        app: santander-experience-backend
    spec:
      containers:
      - name: santander-experience-backend
        image: public.ecr.aws/s5b5p2z2/genai-experience:latest
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: santander-experience-backend-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: santander-experience-backend
