---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: santander-experience-frontend
  labels:
    app: santander-experience-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: santander-experience-frontend
  template:
    metadata:
      labels:
        app: santander-experience-frontend
    spec:
      containers:
      - name: santander-experience-frontend
        image: YOUR_IMAGE
        ports:
        - containerPort: 8501
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: santander-experience-frontend-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8501
  selector:
    app: santander-experience-frontend
